sudo: required

cache:
  npm: false

services:
  - docker

before_install:
  - docker build -t luvwadhwani/docker-react-deployment -f Dockerfile.dev .

script:
  - docker run -e CI=true luvwadhwani/docker-react-deployment npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "frontend"
  environment: "Frontend-env"
  bucket_name: "elasticbeanstalk-ap-south-1-533266976984"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY