sudo: required

cache:
  npm: false

services:
  - docker

before_install:
  - docker build -t luvwadhwani/docker-react-deployment -f Dockerfile.dev .

script:
  - docker run -e CI=true luvwadhwani/docker-react-deployment npm run test